POST http://localhost:8080/login
Content-Type: application/json

{
  "userId": 100001,
  "password": "123456"
}

###

GET http://localhost:8080/api/balances
Authorization: Bearer [Fetch from login operation]

### 

POST http://localhost:8080/api/transactions
Authorization: Bearer [Fetch from login operation]
Content-Type: application/json

{
  "sender": 100001,
  "reciever": 100002,
  "amount": 2000
}

### 

GET http://localhost:8080/api/transactions
Authorization: Bearer [Fetch from login operation]
